version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona-frontend-app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: ["npm", "run", "dev"]
