version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona-frontend-app
    environment:
      SERVER_URL: http://localhost:4000
    restart: always
    ports:
      - 5173:5173
