version: "3"
services:
  web:
    build:
      context: .
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
      dockerfile: Dockerfile
    container_name: persona-frontend-app
    restart: always
    ports:
      - 8080:80
